apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-ms
  namespace: order-ms
  labels:
    app: order-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-ms
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: order-ms
    spec:
      containers:
        - name: order-ms
          image: quanghongphuoc/order-ms:${IMAGE_TAG:-latest}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-ms
  namespace: order-ms
spec:
  selector:
    app: order-ms
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080