apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRllwTFhwMHRad2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBMk1UQXlNekkwTVRWYUZ3MHpOVEEyTURneU16STVNVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN3NS8wRS9CN2xHWTN6NmtOUEZWOEtyVDFER3FJeWM4VFR6YmJUZ1V1TEM4dHprTGpmb01GSjZzR2EKVUd0d29NUkVBTzJFNXB3WDY5bnJibTZSbmpORy9FV2VjSW1kbFB0L0lNaEtQTnVjMkpWeVljRUh5SWFVdlMwSwpWanFjcHVkVG1TOWhjd0o4Z3AyU2VJYUdNR2J4dGFVOHZleUNzM214VHZLMTB4aFZrRkdxSDJVTG5UQlJQTlUzCjVpTmlzUzJXZ0k1QmhKRHhBOUgwRDFldWN2aC9qQmtKZGoySnZJYm13TWp2S215d2ppYi9SUHJjdldnWWRoTXIKOEgzOXMrUGVXbU5OSFlRNzN6T3NRZ3NVNVJ4aWRYa1krZ29kQU1kTzJVWjhMODc1SkJ4Z3QvQUNGb0x0dS8vaQpCaXNtNHN1MGErcHVPbjJocVdRZm1TRmpsWE9uQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSV1A3dnJUME1ISFF3L2ZsMXdFenBnTVpwWjhEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQW5UNEFxM2hkcgorQzZNY09Yb0JXQ1M5ZlhWallNTmRBUE1MY0xuYXBKamNxZ25QenVHTGIram8ybmxxTFVVS09rWTNFRERrTXp0CjVuOHdlcFJnTFhYVkV3OEUwK3Jhc2IyS1FrdVJUVURvVHYzR3NjWUo4NVJ0K0o2SHJ1cFliRmRKSEtUbGRwSUoKK2Rka2hOU3grZW50b2t5MnFPTjBtS3JKa1d3TTUrZHFnaWhsY3g5TThzWEEyQzU0dDU3QzVqRmlhYlA1ZFovYgpnam1sY2lNTldWblhDak83bnZSSk8rRy8yME1pdlROKzZpaXNoOEtrMVAwcU9hMGhzQ1U0U0c2eStHN2pjOG14CkhZVkJOeGc2V3l1YVRWd3hZcnhSZis4VVNkNGZsYm04M1hxd2ZwVHJTMUlRVFRNYmNoU25yVndLQUMraUVVWm0KeS9VMjRya0t6dk1RCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://0F41AC1205AA0C560BE053CE545B68DD.gr7.us-west-2.eks.amazonaws.com
    name: arn:aws:eks:us-west-2:011243863866:cluster/order-ms-cluster
contexts:
  - context:
      cluster: arn:aws:eks:us-west-2:011243863866:cluster/order-ms-cluster
      user: arn:aws:eks:us-west-2:011243863866:cluster/order-ms-cluster
    name: arn:aws:eks:us-west-2:011243863866:cluster/order-ms-cluster
current-context: arn:aws:eks:us-west-2:011243863866:cluster/order-ms-cluster
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:us-west-2:011243863866:cluster/order-ms-cluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - us-west-2
          - eks
          - get-token
          - --cluster-name
          - order-ms-cluster
          - --output
          - json
        command: aws